sudo: required

language: generic 

services:
  - docker

before-install:
  - docker build -t mac/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true mac/docker-react npm run test -- --coverage

